name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: testjhjvujfdvnifdjvckjfdnkjvfd
      uses: ./
      with:
        who-to-greet: 'Mona the Octocat'
        
